// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import NewReleaseController from "./admin/new_release_controller"
application.register("new-release", NewReleaseController)

// legacy controllers
import "./legacy"
