// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "../application"

import NewReleaseController from "./new_release_controller"
application.register("admin-new-release", NewReleaseController)

import ServiceController from "./service_controller"
application.register("admin-service", ServiceController)