#!/usr/bin/with-contenv sh

CORES=$(cat /proc/cpuinfo | grep -c "cpu cores")

REDIS_CONFIG='/etc/redis.conf'

sed -i 's/^\(bind .*\)$/# \1/' $REDIS_CONFIG
sed -i 's/^\(daemonize .*\)$/# \1/' $REDIS_CONFIG
# sed -i 's/^\(logfile\) \(.*\)$/\1 \/app\/logs\/redis-server.log/' $REDIS_CONFIG
# sed -i 's/^\(dir\) \(.*\)$/\1 \/app\/data/redis/' $REDIS_CONFIG
