#!/usr/bin/with-contenv sh

cd /app

# Clear pid if unexpected exception exit
s6-setuidgid zealot rm -f tmp/pids/.pid
s6-setuidgid zealot mkdir -p tmp/pids tmp/cache tmp/uploads tmp/sockets log

# Updating assets
if [ -d "new_public" ]; then
  echo "Zealot updating public ..."
  for x in public/*; do
    if [ -z $(echo "$x" | grep uploads) ]; then
      s6-setuidgid zealot rm -rf "$x"
    fi
  done

  for x in new_public/*; do
    if [ -z $(echo "$x" | grep uploads) ]; then
      s6-setuidgid zealot mv "$x" "public"
    fi
  done

  s6-setuidgid zealot rm -rf new_public
fi