#!/usr/bin/with-contenv sh

cd /app

# Clear pid if unexpected exception exit
rm -f tmp/pids/.pid
mkdir -p tmp/pids tmp/cache tmp/uploads tmp/sockets log

echo ""
echo "Zealot 6.0 is comming soon, here is some changes: "
echo " * redis is not requires as a dependency, you can remove it saftly."
echo " * NEW WEB UI desgin rewrite, feedback is welcome with any issue."
echo " * Swagger API explorer is buit-in."
echo ""

if [ -n "$REDIS_URL" ]; then
  echo
  case $REDIS_URL in
    *redis:*|localhost:*|127.0.0.1:*)
      echo "[WARN] Detected REDIS_URL and redis service, you can remove redis service and the variable."
      ;;
    *)
      echo "[WARN] Detected REDIS_URL variable, you can remove the variable."
      ;;
  esac
fi
