name: Publish Codespace Docker Image

on:
  push:
    paths:
      - '.github/workflows/publish_codespace.yml'
      - '.devcontainer/Dockerfile.base'
      - '.mise.toml'
    branches:
      - develop
  workflow_dispatch:

jobs:
  publish_codespace_image:
    name: Push Codespace Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile.base
          push: true
          labels: |
            org.opencontainers.image.title=Zealot Codespace
            org.opencontainers.image.description=Zealot development workspace
          tags: |
            tryzealot/codespace:latest
            ghcr.io/tryzealot/codespace:latest
          platforms: linux/amd64
